# Generated by Django 4.1.2 on 2022-10-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_timetrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrial',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
