# Generated by Django 4.1.2 on 2022-10-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_level_alter_timetrial_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrial',
            name='full_run',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
