# Generated by Django 4.1.2 on 2022-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_timetrial_full_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrial',
            name='full_run',
            field=models.BooleanField(default=False),
        ),
    ]
